### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by TripGotchu** [Doflerim/discord-server-cloner#1]
Traceback (most recent call last):
  File "C:\Users\miask\downloads\jsd.py", line 55, in <module>
    client.run(token, bot=False)
  File "C:\Users\miask\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 631, in run   
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\miask\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 610, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\miask\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 571, in start 
    raise TypeError("unexpected keyword argument(s) %s" % list(kwargs.keys()))
TypeError: unexpected keyword argument(s) ['bot']

**Comment by TripGotchu** [comment]
Traceback (most recent call last):
  File "C:\Users\miask\downloads\aas.py", line 21, in <module>
    client = commands.Bot(command_prefix=prefix, case_insensitive=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BotBase.__init__() missing 1 required keyword-only argument: 'intents'
